#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <output_filename>"
    exit 1
fi

output_file="$1"

cat > "$output_file" << EOF
#define _GNU_SOURCE   // avverte che usiamo le estensioni GNU 
#include <stdio.h>    // permette di usare scanf printf etc ...
#include <stdlib.h>   // conversioni stringa/numero exit() etc ...
#include <bool.h>  // gestisce tipo bool
#include <assert.h>   // permette di usare la funzione assert
#include <string.h>   // funzioni per stringhe
#include <errno.h>    // rischiesto per usare errno

int main(int argc, char *argv[]) {

    return 0;
}

EOF

echo "Created $output_file"
mfile