#!/bin/bash
input_video="input.mp4"
output_video="output.mp4"
max_bitrate=4096000

while getopts ":li:o:" o; do
    case ${o} in
        l)
            max_bitrate=819200
            ;;
        i)
            input_video=${OPTARG}
            ;;
        o)
            output_video=${OPTARG}
            ;;
    esac
done

bitrate=$(ffprobe -v error -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1:nokey=1 "$input_video")

if [ "$bitrate" -gt "$max_bitrate" ]; then
    bitrate="$max_bitrate"
fi

ffmpeg -i "$input_video" \
       -vf 'scale=1280:720:force_original_aspect_ratio=decrease:flags=fast_bilinear,split[original][copy];[copy]scale=32:18:force_original_aspect_ratio=increase:flags=fast_bilinear,gblur=sigma=2,scale=1280:720:flags=fast_bilinear[blurred];[blurred][original]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2,setsar=1' \
       -c:v h264_videotoolbox \
       -b:v "$bitrate" \
       "$output_video"